gen vcode = .
replace vcode = 3 if country == "Mexico"
replace vcode = 3 if country == "MEXICO"
replace vcode = 4 if country == "Surinam"
replace vcode = 4 if country == "Suriname"
replace vcode = 4 if country == "SURINAME"
replace vcode = 5 if country == "Sweden"
replace vcode = 5 if country == "SWEDEN"
replace vcode = 6 if country == "Switzerland"
replace vcode = 6 if country == "SWITZERLAND"
replace vcode = 7 if country == "Ghana"
replace vcode = 7 if country == "GHANA"
replace vcode = 8 if country == "Cape Colony/ South Africa"
replace vcode = 8 if country == "CAPE COLONY/ SOUTH AFRICA"
replace vcode = 8 if country == "Southafrica"
replace vcode = 8 if country == "SouthAfrica"
replace vcode = 8 if country == "South africa"
replace vcode = 8 if country == "South Africa"
replace vcode = 8 if country == "SOUTH AFRICA"
replace vcode = 9 if country == "Japan"
replace vcode = 9 if country == "JAPAN"
replace vcode = 10 if country == "Burma"
replace vcode = 10 if country == "BURMA"
replace vcode = 10 if country == "Burma_Myanmar"
replace vcode = 10 if country == "Burma/Myanmar"
replace vcode = 10 if country == "BURMA/MYANMAR"
replace vcode = 10 if country == "Myanmar"
replace vcode = 10 if country == "MYANMAR"
replace vcode = 10 if country == "Myanmar (Burma)"
replace vcode = 10 if country == "Myanmar(Burma)"
replace vcode = 11 if country == "Russia"
replace vcode = 11 if country == "RUSSIA"
replace vcode = 11 if country == "Russian Federation"
replace vcode = 11 if country == "RUSSIAN FEDERATION"
replace vcode = 11 if country == "Russia (Soviet Union)"
replace vcode = 11 if country == "Russia/U.S.S.R."
replace vcode = 11 if country == "USSR"
replace vcode = 11 if country == "U.S.S.R."
replace vcode = 12 if country == "Albania"
replace vcode = 12 if country == "ALBANIA"
replace vcode = 13 if country == "Egypt"
replace vcode = 13 if country == "EGYPT"
replace vcode = 13 if country == "Egypt, Arab Rep."
replace vcode = 14 if country == "Yemen"
replace vcode = 14 if country == "YEMEN"
replace vcode = 14 if country == "Yemen Arab Republic"
replace vcode = 14 if country == "Yemen, Arab Republic of"
replace vcode = 14 if country == "Yemen (Arab Republic of Yemen)"
replace vcode = 14 if country == "Yemen (Arab Republic Of Yemen)"
replace vcode = 14 if country == "Yemen, N.Arab"
replace vcode = 14 if country == "Yemen:North"
replace vcode = 14 if country == "Yemen, People'S Republic Of"
replace vcode = 14 if country == "Yemen, Rep."
replace vcode = 15 if country == "Colombia"
replace vcode = 15 if country == "COLOMBIA"
replace vcode = 15 if country == "Columbia"
replace vcode = 17 if country == "Poland"
replace vcode = 17 if country == "POLAND"
replace vcode = 19 if country == "Brasil"
replace vcode = 19 if country == "Brazil"
replace vcode = 19 if country == "BRAZIL"
replace vcode = 20 if country == "Unitedstates"
replace vcode = 20 if country == "United States"
replace vcode = 20 if country == "UNITED STATES"
replace vcode = 20 if country == "United States of America"
replace vcode = 20 if country == "United States Of America"
replace vcode = 20 if country == "UNITED STATES OF AMERICA"
replace vcode = 20 if country == "US"
replace vcode = 20 if country == "USA"
replace vcode = 20 if country == "U.S.A"
replace vcode = 20 if country == "U.S.A."
replace vcode = 21 if country == "Portugal"
replace vcode = 21 if country == "PORTUGAL"
replace vcode = 22 if country == "Elsalvador"
replace vcode = 22 if country == "El salvador"
replace vcode = 22 if country == "El Salvador"
replace vcode = 22 if country == "EL SALVADOR"
replace vcode = 23 if country == "South Yemen"
replace vcode = 23 if country == "SOUTH YEMEN"
replace vcode = 23 if country == "Yemen, People's Democratic Republic of"
replace vcode = 23 if country == "Yemen People's Republic"
replace vcode = 23 if country == "Yemen, People's Republic of"
replace vcode = 23 if country == "Yemen, South"
replace vcode = 23 if country == "Yemen:South"
replace vcode = 23 if country == "YEMEN, SOUTH"
replace vcode = 24 if country == "Bangladesh"
replace vcode = 24 if country == "BANGLADESH"
replace vcode = 25 if country == "Bolivia"
replace vcode = 25 if country == "BOLIVIA"
replace vcode = 25 if country == "Bolivia (Plurinational State of)"
replace vcode = 26 if country == "Haiti"
replace vcode = 26 if country == "HAITI"
replace vcode = 26 if country == "Haíti"
replace vcode = 26 if country == "HAÍTI"
replace vcode = 26 if country == "Haïti"
replace vcode = 27 if country == "Honduras"
replace vcode = 27 if country == "HONDURAS"
replace vcode = 28 if country == "Mali"
replace vcode = 28 if country == "MALI"
replace vcode = 29 if country == "Pakistan"
replace vcode = 29 if country == "PAKISTAN"
replace vcode = 29 if country == "Pakistan-post-1972"
replace vcode = 30 if country == "Peru"
replace vcode = 30 if country == "PERU"
replace vcode = 31 if country == "Senegal"
replace vcode = 31 if country == "SENEGAL"
replace vcode = 32 if country == "South Sudan"
replace vcode = 32 if country == "SOUTH SUDAN"
replace vcode = 33 if country == "Sudan"
replace vcode = 33 if country == "SUDAN"
replace vcode = 34 if country == "Vietnam"
replace vcode = 34 if country == "Viet Nam"
replace vcode = 34 if country == "VIETNAM"
replace vcode = 34 if country == "VIET NAM"
replace vcode = 34 if country == "Vietnam (Annam/Cochin China/Tonkin)"
replace vcode = 34 if country == "Vietnam_Democratic Republic of"
replace vcode = 34 if country == "Vietnam, Democratic Republic of"
replace vcode = 34 if country == "Vietnam, Democratic Republic Of"
replace vcode = 34 if country == "VIETNAM, DEMOCRATIC REPUBLIC OF"
replace vcode = 34 if country == "Vietnam, North"
replace vcode = 35 if country == "Republic of Vietnam"
replace vcode = 35 if country == "Vietnam_Republic of"
replace vcode = 35 if country == "Vietnam, Republic of"
replace vcode = 35 if country == "Vietnam, Republic Of"
replace vcode = 35 if country == "VIETNAM, REPUBLIC OF"
replace vcode = 35 if country == "Vietnam, South"
replace vcode = 36 if country == "Afghanistan"
replace vcode = 36 if country == "AFGHANISTAN"
replace vcode = 36 if country == "Afghanistan, I.R. of"
replace vcode = 37 if country == "Argentina"
replace vcode = 37 if country == "ARGENTINA"
replace vcode = 37 if country == "Argentine"
replace vcode = 38 if country == "Ethiopia"
replace vcode = 38 if country == "ETHIOPIA"
replace vcode = 39 if country == "India"
replace vcode = 39 if country == "INDIA"
replace vcode = 40 if country == "Kenya"
replace vcode = 40 if country == "KENYA"
replace vcode = 41 if country == "Democratic People's Republic of Korea"
replace vcode = 41 if country == "Korea, Democratic People's Republic"
replace vcode = 41 if country == "Korea, Dem. People's Rep."
replace vcode = 41 if country == "Korea, Dem. People’s Rep."
replace vcode = 41 if country == "Korea, Dem. Rep."
replace vcode = 41 if country == "Korea,Dem.Rep."
replace vcode = 41 if country == "Korea_North"
replace vcode = 41 if country == "Korea, North"
replace vcode = 41 if country == "Korea:North"
replace vcode = 41 if country == "KOREA, NORTH"
replace vcode = 41 if country == "Korea, People's Republic of"
replace vcode = 41 if country == "Korea, People'S Republic Of"
replace vcode = 41 if country == "North Korea"
replace vcode = 41 if country == "NORTH KOREA"
replace vcode = 42 if country == "Korea"
replace vcode = 42 if country == "Korea, rep."
replace vcode = 42 if country == "Korea, Rep."
replace vcode = 42 if country == "Korea, Republic of"
replace vcode = 42 if country == "Korea, Republic Of"
replace vcode = 42 if country == "Korea South"
replace vcode = 42 if country == "SouthKorea"
replace vcode = 42 if country == "Korea_South"
replace vcode = 42 if country == "Korea, South"
replace vcode = 42 if country == "Korea:South"
replace vcode = 42 if country == "KOREA, SOUTH"
replace vcode = 42 if country == "Republic of Korea"
replace vcode = 42 if country == "S. Korea"
replace vcode = 42 if country == "S. KOREA"
replace vcode = 42 if country == "South Korea"
replace vcode = 42 if country == "SOUTH KOREA"
replace vcode = 43 if country == "Kosovo"
replace vcode = 43 if country == "KOSOVO"
replace vcode = 44 if country == "Lebanon"
replace vcode = 44 if country == "LEBANON"
replace vcode = 45 if country == "Nigeria"
replace vcode = 45 if country == "NIGERIA"
replace vcode = 46 if country == "Philippines"
replace vcode = 46 if country == "PHILIPPINES"
replace vcode = 46 if country == "Phillipines"
replace vcode = 47 if country == "Tanzania"
replace vcode = 47 if country == "TANZANIA"
replace vcode = 47 if country == "Tanzania:Tanganyika"
replace vcode = 47 if country == "Tanzania/Tanganyika"
replace vcode = 47 if country == "Tanzania, United Republic of"
replace vcode = 47 if country == "Tanzania:Zanzibar"
replace vcode = 47 if country == "United Republic of Tanzania"
replace vcode = 47 if country == "Zanzibar"
replace vcode = 48 if country == "Taipei, Chinese"
replace vcode = 48 if country == "Taiwan"
replace vcode = 48 if country == "TAIWAN"
replace vcode = 48 if country == "Taiwan, China"
replace vcode = 48 if country == "Taiwan, Province of China"
replace vcode = 49 if country == "Thailand"
replace vcode = 49 if country == "THAILAND"
replace vcode = 49 if country == "Siam"
replace vcode = 50 if country == "Uganda"
replace vcode = 50 if country == "UGANDA"
replace vcode = 51 if country == "Venezuela"
replace vcode = 51 if country == "VENEZUELA"
replace vcode = 51 if country == "Venezuela, Bolivarian Republic of"
replace vcode = 51 if country == "VENEZUELA, BOLIVARIAN REPUBLIC OF"
replace vcode = 51 if country == "Venezuela, RB"
replace vcode = 51 if country == "Venezuela, Rep. Bol."
replace vcode = 52 if country == "Benin"
replace vcode = 52 if country == "BENIN"
replace vcode = 53 if country == "Bhutan"
replace vcode = 53 if country == "BHUTAN"
replace vcode = 54 if country == "Burkinafaso"
replace vcode = 54 if country == "Burkina faso"
replace vcode = 54 if country == "Burkina Faso"
replace vcode = 54 if country == "BURKINA FASO"
replace vcode = 54 if country == "Burkina Faso (Upper Volta)"
replace vcode = 55 if country == "Cambodia"
replace vcode = 55 if country == "CAMBODIA"
replace vcode = 55 if country == "Cambodia (Kampuchea)"
replace vcode = 55 if country == "Kampuchea, Democratic"
replace vcode = 56 if country == "Indonesia"
replace vcode = 56 if country == "INDONESIA"
replace vcode = 57 if country == "Mozambique"
replace vcode = 57 if country == "MOZAMBIQUE"
replace vcode = 58 if country == "Nepal"
replace vcode = 58 if country == "NEPAL"
replace vcode = 59 if country == "Nicaragua"
replace vcode = 59 if country == "NICARAGUA"
replace vcode = 60 if country == "Niger"
replace vcode = 60 if country == "NIGER"
replace vcode = 61 if country == "Zambia"
replace vcode = 61 if country == "ZAMBIA"
replace vcode = 62 if country == "Zimbabwe"
replace vcode = 62 if country == "ZIMBABWE"
replace vcode = 62 if country == "Zimbabwe (Rhodesia)"
replace vcode = 63 if country == "Guinea"
replace vcode = 63 if country == "GUINEA"
replace vcode = 64 if country == "Cote dIvoire"
replace vcode = 64 if country == "Cote d'Ivoire"
replace vcode = 64 if country == "Cote d’Ivoire"
replace vcode = 64 if country == "Cote D'Ivoire"
replace vcode = 64 if country == "Côte d'Ivoire"
replace vcode = 64 if country == "Côte d’Ivoire"
replace vcode = 64 if country == "Côte D'Ivoire"
replace vcode = 64 if country == "CÔTE D'IVOIRE"
replace vcode = 64 if country == "Cote d'Ivoire (Ivory Coast)"
replace vcode = 64 if country == "COTE D'IVOIRE (IVORY COAST)"
replace vcode = 64 if country == "Cote d'lvoire"
replace vcode = 64 if country == "Ivorycoast"
replace vcode = 64 if country == "Ivory Coast"
replace vcode = 64 if country == "IVORY COAST"
replace vcode = 65 if country == "Mauritania"
replace vcode = 65 if country == "MAURITANIA"
replace vcode = 65 if country == "Mauritania, Islamic"
replace vcode = 66 if country == "Canada"
replace vcode = 66 if country == "CANADA"
replace vcode = 67 if country == "Australia"
replace vcode = 67 if country == "AUSTRALIA"
replace vcode = 68 if country == "Bechuanaland"
replace vcode = 68 if country == "Botswana"
replace vcode = 68 if country == "BOTSWANA"
replace vcode = 69 if country == "Burundi"
replace vcode = 69 if country == "BURUNDI"
replace vcode = 70 if country == "Cabo Verde"
replace vcode = 70 if country == "Capeverde"
replace vcode = 70 if country == "Cape Verde"
replace vcode = 70 if country == "CAPE VERDE"
replace vcode = 70 if country == "Cape Verde Is."
replace vcode = 70 if country == "Cape Verde Island"
replace vcode = 70 if country == "Cape Verde Island"
replace vcode = 71 if country == "Cear"
replace vcode = 71 if country == "Centr. Afr. Rep."
replace vcode = 71 if country == "CENTR. AFR. REP."
replace vcode = 71 if country == "Central African Rep"
replace vcode = 71 if country == "Central African Rep"
replace vcode = 71 if country == "Central African Rep."
replace vcode = 71 if country == "Central African Republic"
replace vcode = 71 if country == "CENTRAL AFRICAN REPUBLIC"
replace vcode = 71 if country == "Central Afr.R."
replace vcode = 71 if country == "Central Afr. Rep."
replace vcode = 72 if country == "Chile"
replace vcode = 72 if country == "CHILE"
replace vcode = 73 if country == "Costarica"
replace vcode = 73 if country == "Costa rica"
replace vcode = 73 if country == "CostaRica"
replace vcode = 73 if country == "Costa Rica"
replace vcode = 73 if country == "COSTA RICA"
replace vcode = 74 if country == "Easttimor"
replace vcode = 74 if country == "East Timor"
replace vcode = 74 if country == "EAST TIMOR"
replace vcode = 74 if country == "Timor"
replace vcode = 74 if country == "Timore-Leste"
replace vcode = 74 if country == "Timor Leste"
replace vcode = 74 if country == "Timor-Leste"
replace vcode = 74 if country == "Timor-Leste (East Timor)"
replace vcode = 74 if country == "TIMOR-LESTE (EAST TIMOR)"
replace vcode = 75 if country == "Ecuador"
replace vcode = 75 if country == "ECUADOR"
replace vcode = 76 if country == "France"
replace vcode = 76 if country == "FRANCE"
replace vcode = 77 if country == "Federal Republic of Germany"
replace vcode = 77 if country == "German Federal Republic"
replace vcode = 77 if country == "Germany"
replace vcode = 77 if country == "GERMANY"
replace vcode = 77 if country == "Germany, Federal Republic of"
replace vcode = 77 if country == "Germany (Prussia)"
replace vcode = 77 if country == "Germany, West"
replace vcode = 77 if country == "Germany:West"
replace vcode = 78 if country == "Guatemala"
replace vcode = 78 if country == "GUATEMALA"
replace vcode = 79 if country == "Iran"
replace vcode = 79 if country == "IRAN"
replace vcode = 79 if country == "Iran, I.R. of"
replace vcode = 79 if country == "Iran, Islamic Rep."
replace vcode = 79 if country == "Iran (Islamic Republic of)"
replace vcode = 79 if country == "Iran, Islamic Republic of"
replace vcode = 79 if country == "IRAN, ISLAMIC REPUBLIC OF"
replace vcode = 79 if country == "Iran (Persia)"
replace vcode = 80 if country == "Iraq"
replace vcode = 80 if country == "IRAQ"
replace vcode = 81 if country == "Ireland"
replace vcode = 81 if country == "IRELAND"
replace vcode = 81 if country == "Ireland:Republic"
replace vcode = 82 if country == "Italy"
replace vcode = 82 if country == "ITALY"
replace vcode = 82 if country == "Italy/Sardinia"
replace vcode = 83 if country == "Jordan"
replace vcode = 83 if country == "JORDAN"
replace vcode = 84 if country == "Latvia"
replace vcode = 84 if country == "LATVIA"
replace vcode = 85 if country == "Basutoland"
replace vcode = 85 if country == "Lesotho"
replace vcode = 85 if country == "LESOTHO"
replace vcode = 86 if country == "Liberia"
replace vcode = 86 if country == "LIBERIA"
replace vcode = 87 if country == "Malawi"
replace vcode = 87 if country == "MALAWI"
replace vcode = 88 if country == "Maldives"
replace vcode = 88 if country == "MALDIVES"
replace vcode = 89 if country == "Mongolia"
replace vcode = 89 if country == "MONGOLIA"
replace vcode = 90 if country == "Morocco"
replace vcode = 90 if country == "MOROCCO"
replace vcode = 91 if country == "Holland"
replace vcode = 91 if country == "HOLLAND"
replace vcode = 91 if country == "Netherlands"
replace vcode = 91 if country == "NETHERLANDS"
replace vcode = 91 if country == "Netherlands, The"
replace vcode = 92 if country == "Panama"
replace vcode = 92 if country == "PANAMA"
replace vcode = 93 if country == "Pap. New Guinea"
replace vcode = 93 if country == "Papua New Guinea"
replace vcode = 93 if country == "Papua-New Guinea"
replace vcode = 93 if country == "PAPUA NEW GUINEA"
replace vcode = 93 if country == "Papua New Guninea"
replace vcode = 93 if country == "Papuang"
replace vcode = 93 if country == "Papua n.guinea"
replace vcode = 94 if country == "Qatar"
replace vcode = 94 if country == "QATAR"
replace vcode = 95 if country == "Sierraleone"
replace vcode = 95 if country == "Sierra leone"
replace vcode = 95 if country == "Sierra Leone"
replace vcode = 95 if country == "SIERRA LEONE"
replace vcode = 96 if country == "Spain"
replace vcode = 96 if country == "SPAIN"
replace vcode = 97 if country == "Syria"
replace vcode = 97 if country == "SYRIA"
replace vcode = 97 if country == "Syrian Arab Republic"
replace vcode = 97 if country == "Syria (Syrian Arab Republic)"
replace vcode = 97 if country == "SYRIA (SYRIAN ARAB REPUBLIC)"
replace vcode = 98 if country == "Tunisia"
replace vcode = 98 if country == "TUNISIA"
replace vcode = 99 if country == "Turkey"
replace vcode = 99 if country == "TURKEY"
replace vcode = 99 if country == "Turkey (Ottoman Empire)"
replace vcode = 99 if country == "Turkey/Ottoman Empire"
replace vcode = 100 if country == "Ukraine"
replace vcode = 100 if country == "UKRAINE"
replace vcode = 101 if country == "England"
replace vcode = 101 if country == "England/GB/UK"
replace vcode = 101 if country == "ENGLAND/GB/UK"
replace vcode = 101 if country == "Great Britain"
replace vcode = 101 if country == "GreatBritain"
replace vcode = 101 if country == "Ireland:Northern"
replace vcode = 101 if country == "UK"
replace vcode = 101 if country == "U.K."
replace vcode = 101 if country == "United Kingdom"
replace vcode = 101 if country == "UNITED KINGDOM"
replace vcode = 101 if country == "United Kingdom (Great Britain)"
replace vcode = 101 if country == "UNITED KINGDOM (GREAT BRITAIN)"
replace vcode = 101 if country == "United Kingdom of Great Britain and Northern Ireland"
replace vcode = 102 if country == "Uraguay"
replace vcode = 102 if country == "Uruguay"
replace vcode = 102 if country == "URUGUAY"
replace vcode = 103 if country == "Algeria"
replace vcode = 103 if country == "ALGERIA"
replace vcode = 104 if country == "Angola"
replace vcode = 104 if country == "ANGOLA"
replace vcode = 105 if country == "Armenia"
replace vcode = 105 if country == "ARMENIA"
replace vcode = 106 if country == "Azarbaijan"
replace vcode = 106 if country == "Azerbaijan"
replace vcode = 106 if country == "AZERBAIJAN"
replace vcode = 106 if country == "Azerbaijan, Rep. of"
replace vcode = 107 if country == "Belarus"
replace vcode = 107 if country == "BELARUS"
replace vcode = 107 if country == "Belarus (Byelorussia)"
replace vcode = 108 if country == "Cameroon"
replace vcode = 108 if country == "CAMEROON"
replace vcode = 108 if country == "Cameroon:British"
replace vcode = 108 if country == "Cameroon:French"
replace vcode = 109 if country == "Chad"
replace vcode = 109 if country == "CHAD"
replace vcode = 110 if country == "China"
replace vcode = 110 if country == "CHINA"
replace vcode = 110 if country == "China, Mainland"
replace vcode = 110 if country == "China, People's Republic of"
replace vcode = 110 if country == "CHINA, PEOPLE'S REPUBLIC OF"
replace vcode = 111 if country == "Congo, Democratic Republic"
replace vcode = 111 if country == "Congo_Democratic Republic of"
replace vcode = 111 if country == "Congo, Democratic Republic of"
replace vcode = 111 if country == "CONGO, DEMOCRATIC REPUBLIC OF"
replace vcode = 111 if country == "Congo, Democratic Republic of the"
replace vcode = 111 if country == "CONGO, DEMOCRATIC REPUBLIC OF THE"
replace vcode = 111 if country == "Congo, Democratic Republic of (Zaire)"
replace vcode = 111 if country == "Congo, Democratic Republic Of (Zaire)"
replace vcode = 111 if country == "Congo, Dem. R."
replace vcode = 111 if country == "Congo, Dem. Rep."
replace vcode = 111 if country == "Congo, Dem. Rep. of"
replace vcode = 111 if country == "Congo, Dem. Rep. Of the "
replace vcode = 111 if country == "Congodr"
replace vcode = 111 if country == "Congo DR"
replace vcode = 111 if country == "Congo, DRC"
replace vcode = 111 if country == "Congo-Kinshasa"
replace vcode = 111 if country == "Congo - Kinshasa"
replace vcode = 111 if country == "CONGO-KINSHASA"
replace vcode = 111 if country == "Democratic Republic of Congo"
replace vcode = 111 if country == "Democratic Republic of the Congo"
replace vcode = 111 if country == "DRC"
replace vcode = 111 if country == "Zaire"
replace vcode = 111 if country == "ZAIRE"
replace vcode = 111 if country == "Zaire (Congo Kinshasa)"
replace vcode = 111 if country == "Zaire (Congo-Kinshasa)"
replace vcode = 111 if country == "ZAIRE (CONGO KINSHASA)"
replace vcode = 112 if country == "Congo"
replace vcode = 112 if country == "Congo Brazzaville"
replace vcode = 112 if country == "Congo - Brazzaville"
replace vcode = 112 if country == "Congo 'Brazzaville'"
replace vcode = 112 if country == "CONGO 'BRAZZAVILLE'"
replace vcode = 112 if country == "Congo, Rep."
replace vcode = 112 if country == "Congo, Rep. Of"
replace vcode = 112 if country == "Congo, Rep. Of the "
replace vcode = 112 if country == "Congo, Republic of"
replace vcode = 112 if country == "Congo_Republic of the"
replace vcode = 112 if country == "Congo, Republic of the"
replace vcode = 112 if country == "CONGO, REPUBLIC OF THE"
replace vcode = 112 if country == "Congo, the Republic of the"
replace vcode = 112 if country == "Republic of Congo"
replace vcode = 112 if country == "Republic of the Congo"
replace vcode = 113 if country == "Djibouti"
replace vcode = 113 if country == "DJIBOUTI"
replace vcode = 114 if country == "Dominican rep."
replace vcode = 114 if country == "DominicanRepublic"
replace vcode = 114 if country == "DominicanRep"
replace vcode = 114 if country == "Dominican Rep."
replace vcode = 114 if country == "DOMINICAN REP."
replace vcode = 114 if country == "Dominicanrepublic"
replace vcode = 114 if country == "Dominican Republic"
replace vcode = 114 if country == "DOMINICAN REPUBLIC"
replace vcode = 115 if country == "Eritrea"
replace vcode = 115 if country == "ERITREA"
replace vcode = 116 if country == "Gabon"
replace vcode = 116 if country == "GABON"
replace vcode = 117 if country == "Gambia"
replace vcode = 117 if country == "GAMBIA"
replace vcode = 117 if country == "Gambia (Islamic Republic of the)"
replace vcode = 117 if country == "Gambia, The"
replace vcode = 117 if country == "Gambia, The "
replace vcode = 117 if country == "The Gambia"
replace vcode = 118 if country == "Georgia"
replace vcode = 118 if country == "GEORGIA"
replace vcode = 119 if country == "Guinea-biss"
replace vcode = 119 if country == "Guinea Bissau"
replace vcode = 119 if country == "Guinea-Bissau"
replace vcode = 119 if country == "GUINEA BISSAU"
replace vcode = 119 if country == "GUINEA-BISSAU"
replace vcode = 120 if country == "Jamaica"
replace vcode = 120 if country == "JAMAICA"
replace vcode = 121 if country == "Kazakhstan"
replace vcode = 121 if country == "KAZAKHSTAN"
replace vcode = 122 if country == "Krgyzistan"
replace vcode = 122 if country == "Krgyz Republic"
replace vcode = 122 if country == "Kyrgyz Republic"
replace vcode = 122 if country == "Kyrgyzstan"
replace vcode = 122 if country == "KYRGYZSTAN"
replace vcode = 123 if country == "Lao PDR"
replace vcode = 123 if country == "Lao People's Democratic Republic"
replace vcode = 123 if country == "Lao People’s Democratic Republic"
replace vcode = 123 if country == "Lao People's Dem.Rep"
replace vcode = 123 if country == "Lao Peoples Republic"
replace vcode = 123 if country == "Lao Republic"
replace vcode = 123 if country == "Laos"
replace vcode = 123 if country == "LAOS"
replace vcode = 124 if country == "Libya"
replace vcode = 124 if country == "LIBYA"
replace vcode = 124 if country == "Libyan Arab Jamahiriya"
replace vcode = 124 if country == "Libyan Arab Jamihiriya"
replace vcode = 125 if country == "Madagascar"
replace vcode = 125 if country == "MADAGASCAR"
replace vcode = 125 if country == "Madagascar (Malagasy)"
replace vcode = 126 if country == "Moldova"
replace vcode = 126 if country == "MOLDOVA"
replace vcode = 126 if country == "Moldova, Republic of"
replace vcode = 126 if country == "MOLDOVA, REPUBLIC OF"
replace vcode = 126 if country == "Republic of Moldova"
replace vcode = 127 if country == "Namibia"
replace vcode = 127 if country == "NAMIBIA"
replace vcode = 128 if country == "Gaza Strip"
replace vcode = 128 if country == "Palestine"
replace vcode = 128 if country == "Palestine_British_Mandate"
replace vcode = 128 if country == "Palestine_Gaza"
replace vcode = 128 if country == "Palestine, State of"
replace vcode = 128 if country == "Palestine (West Bank)"
replace vcode = 128 if country == "Palestine_West_Bank"
replace vcode = 128 if country == "Palestine/West Bank"
replace vcode = 128 if country == "PALESTINE (WEST BANK)"
replace vcode = 128 if country == "PALESTINE/WEST BANK"
replace vcode = 128 if country == "Palestinian Territory"
replace vcode = 128 if country == "West Bank"
replace vcode = 128 if country == "West Bank and Gaza"
replace vcode = 129 if country == "Rwanda"
replace vcode = 129 if country == "RWANDA"
replace vcode = 129 if country == "Rwanda-Urwndi"
replace vcode = 130 if country == "Somali"
replace vcode = 130 if country == "Somalia"
replace vcode = 130 if country == "SOMALIA"
replace vcode = 131 if country == "Ceylon"
replace vcode = 131 if country == "Srilanka"
replace vcode = 131 if country == "SriLanka"
replace vcode = 131 if country == "Sri lanka"
replace vcode = 131 if country == "Sri Lanka"
replace vcode = 131 if country == "SRI LANKA"
replace vcode = 131 if country == "Sri Lanka (Ceylon)"
replace vcode = 132 if country == "Swaziland"
replace vcode = 132 if country == "SWAZILAND"
replace vcode = 133 if country == "Tajikistan"
replace vcode = 133 if country == "TAJIKISTAN"
replace vcode = 134 if country == "Togo"
replace vcode = 134 if country == "TOGO"
replace vcode = 135 if country == "Tobago"
replace vcode = 135 if country == "Trinidad"
replace vcode = 135 if country == "Trinidad and Tobaggo"
replace vcode = 135 if country == "Trinidad and Tobago"
replace vcode = 135 if country == "Trinidad And Tobago"
replace vcode = 135 if country == "TRINIDAD AND TOBAGO"
replace vcode = 135 if country == "Trinidad & Tob."
replace vcode = 135 if country == "Trinidad&tobago"
replace vcode = 135 if country == "Trinidad & Tobago"
replace vcode = 135 if country == "T. & Tobago"
replace vcode = 135 if country == "T. & TOBAGO"
replace vcode = 136 if country == "Turkmenistan"
replace vcode = 136 if country == "TURKMENISTAN"
replace vcode = 137 if country == "German Democratic Republic"
replace vcode = 137 if country == "GERMAN DEMOCRATIC REPUBLIC"
replace vcode = 137 if country == "Germany, East"
replace vcode = 137 if country == "Germany:East"
replace vcode = 138 if country == "Palestine (Gaza)"
replace vcode = 138 if country == "Palestine/Gaza"
replace vcode = 138 if country == "PALESTINE (GAZA)"
replace vcode = 138 if country == "PALESTINE/GAZA"
replace vcode = 139 if country == "Somaliland"
replace vcode = 139 if country == "SOMALILAND"
replace vcode = 140 if country == "Uzbekistan"
replace vcode = 140 if country == "UZBEKISTAN"
replace vcode = 142 if country == "Andorra"
replace vcode = 142 if country == "ANDORRA"
replace vcode = 143 if country == "Antigua"
replace vcode = 143 if country == "Antigua and Barbuda"
replace vcode = 143 if country == "Antigua And Barbuda"
replace vcode = 143 if country == "ANTIGUA AND BARBUDA"
replace vcode = 143 if country == "Antigua & Barbuda"
replace vcode = 143 if country == "Barbuda"
replace vcode = 144 if country == "Austria"
replace vcode = 144 if country == "AUSTRIA"
replace vcode = 144 if country == "Austria-Hungary"
replace vcode = 145 if country == "Bahamas"
replace vcode = 145 if country == "BAHAMAS"
replace vcode = 145 if country == "Bahamas, The"
replace vcode = 145 if country == "Bahamas, The        "
replace vcode = 146 if country == "Bahrain"
replace vcode = 146 if country == "BAHRAIN"
replace vcode = 146 if country == "Bahrain, Kingdom of"
replace vcode = 147 if country == "Barbados"
replace vcode = 147 if country == "BARBADOS"
replace vcode = 148 if country == "Belgium"
replace vcode = 148 if country == "BELGIUM"
replace vcode = 149 if country == "Belize"
replace vcode = 149 if country == "BELIZE"
replace vcode = 149 if country == "British Honduras"
replace vcode = 150 if country == "Bosnia"
replace vcode = 150 if country == "BOSNIA"
replace vcode = 150 if country == "Bosnia and Herzegovina"
replace vcode = 150 if country == "BOSNIA AND HERZEGOVINA"
replace vcode = 150 if country == "Bosnia and Herzigova"
replace vcode = 150 if country == "Bosnia & Herzegovina"
replace vcode = 150 if country == "Bosnia-Herzegovina"
replace vcode = 150 if country == "Bosnia-Herzegovinia"
replace vcode = 151 if country == "Brunei"
replace vcode = 151 if country == "BRUNEI"
replace vcode = 151 if country == "Brunei Darussalam"
replace vcode = 152 if country == "Bulgaria"
replace vcode = 152 if country == "BULGARIA"
replace vcode = 153 if country == "Comoro Islands"
replace vcode = 153 if country == "COMORO ISLANDS"
replace vcode = 153 if country == "Comoros"
replace vcode = 153 if country == "COMOROS"
replace vcode = 154 if country == "Croatia"
replace vcode = 154 if country == "CROATIA"
replace vcode = 155 if country == "Cuba"
replace vcode = 155 if country == "CUBA"
replace vcode = 156 if country == "Cyprus"
replace vcode = 156 if country == "CYPRUS"
replace vcode = 157 if country == "Czech"
replace vcode = 157 if country == "Czechia"
replace vcode = 157 if country == "Czechoslovakia"
replace vcode = 157 if country == "Czech Rep."
replace vcode = 157 if country == "CZECH REP."
replace vcode = 157 if country == "Czech Republic"
replace vcode = 157 if country == "CZECH REPUBLIC"
replace vcode = 157 if country == "Czechia"
replace vcode = 157 if country == "Czechoslovakia"
replace vcode = 157 if country == "Czeck"
replace vcode = 158 if country == "Denmark"
replace vcode = 158 if country == "DENMARK"
replace vcode = 159 if country == "Dominica"
replace vcode = 159 if country == "DOMINICA"
replace vcode = 160 if country == "Equatorialguinea"
replace vcode = 160 if country == "Equatorial Guinea"
replace vcode = 160 if country == "EQUATORIAL GUINEA"
replace vcode = 160 if country == "Equitorial Guinea"
replace vcode = 161 if country == "Estonia"
replace vcode = 161 if country == "ESTONIA"
replace vcode = 162 if country == "Fiji"
replace vcode = 162 if country == "FIJI"
replace vcode = 162 if country == "Fiji Islands"
replace vcode = 163 if country == "Finland"
replace vcode = 163 if country == "FINLAND"
replace vcode = 164 if country == "Greece"
replace vcode = 164 if country == "GREECE"
replace vcode = 165 if country == "Grenada"
replace vcode = 165 if country == "GRENADA"
replace vcode = 166 if country == "British Guiana"
replace vcode = 166 if country == "Guyana"
replace vcode = 166 if country == "GUYANA"
replace vcode = 167 if country == "China, Hong Kong"
replace vcode = 167 if country == "China, Hong Kong Special Administrative Region"
replace vcode = 167 if country == "Hongkong"
replace vcode = 167 if country == "Hong Kong"
replace vcode = 167 if country == "HONG KONG"
replace vcode = 167 if country == "Hong Kong SAR China"
replace vcode = 167 if country == "Hong Kong SAR, China"
replace vcode = 167 if country == "Hong Kong, China"
replace vcode = 167 if country == "Hong Kong SAR, China"
replace vcode = 168 if country == "Iceland"
replace vcode = 168 if country == "ICELAND"
replace vcode = 169 if country == "Israel"
replace vcode = 169 if country == "ISRAEL"
replace vcode = 170 if country == "Kiribati"
replace vcode = 170 if country == "KIRIBATI"
replace vcode = 171 if country == "Kuwait"
replace vcode = 171 if country == "KUWAIT"
replace vcode = 172 if country == "Liechtenstein"
replace vcode = 172 if country == "LIECHTENSTEIN"
replace vcode = 173 if country == "Lithuania"
replace vcode = 173 if country == "LITHUANIA"
replace vcode = 174 if country == "Luxembourg"
replace vcode = 174 if country == "LUXEMBOURG"
replace vcode = 175 if country == "China, Macao Special Administrative Region"
replace vcode = 175 if country == "Macao"
replace vcode = 175 if country == "Macao SAR, China"
replace vcode = 175 if country == "Macau"
replace vcode = 175 if country == "MACAU"
replace vcode = 175 if country == "Macau, China"
replace vcode = 176 if country == "Macedonia"
replace vcode = 176 if country == "MACEDONIA"
replace vcode = 176 if country == "Macedonia (Former Yugoslav Republic of)"
replace vcode = 176 if country == "Macedonia (Former Yugoslav Republic Of)"
replace vcode = 176 if country == "Macedonia, FYR"
replace vcode = 176 if country == "Macedonia, The former Yugoslav Rep. of"
replace vcode = 176 if country == "The former Yugoslav Republic of Macedonia"
replace vcode = 177 if country == "Malaya"
replace vcode = 177 if country == "Malaysia"
replace vcode = 177 if country == "MALAYSIA"
replace vcode = 177 if country == "Sabah"
replace vcode = 177 if country == "Sarawak"
replace vcode = 178 if country == "Malta"
replace vcode = 178 if country == "MALTA"
replace vcode = 179 if country == "Marshall Is."
replace vcode = 179 if country == "Marshall Island"
replace vcode = 179 if country == "Marshallislands"
replace vcode = 179 if country == "Marshall Islands"
replace vcode = 179 if country == "MARSHALL ISLANDS"
replace vcode = 180 if country == "Mauritius"
replace vcode = 180 if country == "MAURITIUS"
replace vcode = 180 if country == "Mauritus"
replace vcode = 181 if country == "Federated States of Micronesia"
replace vcode = 181 if country == "Micronesia"
replace vcode = 181 if country == "Micronesia (Federated States of)"
replace vcode = 181 if country == "Micronesia, Federated States of"
replace vcode = 181 if country == "MICRONESIA, FEDERATED STATES OF"
replace vcode = 181 if country == "Micronesia, Fed. Sts."
replace vcode = 182 if country == "Monaco"
replace vcode = 182 if country == "MONACO"
replace vcode = 183 if country == "Montenegro"
replace vcode = 183 if country == "MONTENEGRO"
replace vcode = 184 if country == "Nauru"
replace vcode = 184 if country == "NAURU"
replace vcode = 185 if country == "Newzealand"
replace vcode = 185 if country == "NewZealand"
replace vcode = 185 if country == "New zealand"
replace vcode = 185 if country == "New Zealand"
replace vcode = 185 if country == "NEW ZEALAND"
replace vcode = 185 if country == "N. Zealand"
replace vcode = 185 if country == "N. ZEALAND"
replace vcode = 186 if country == "Norway"
replace vcode = 186 if country == "NORWAY"
replace vcode = 187 if country == "Oman"
replace vcode = 187 if country == "OMAN"
replace vcode = 188 if country == "Palau"
replace vcode = 188 if country == "PALAU"
replace vcode = 188 if country == "Palau Island"
replace vcode = 188 if country == "Palau Island"
replace vcode = 189 if country == "Paraguay"
replace vcode = 189 if country == "Paraguay"
replace vcode = 189 if country == "PARAGUAY"
replace vcode = 190 if country == "Romania"
replace vcode = 190 if country == "ROMANIA"
replace vcode = 190 if country == "Rumania"
replace vcode = 191 if country == "Nevis"
replace vcode = 191 if country == "Saint Kitts"
replace vcode = 191 if country == "Saint Kitts and Nevis"
replace vcode = 191 if country == "SAINT KITTS AND NEVIS"
replace vcode = 191 if country == "Saint Kitts & Nevis"
replace vcode = 191 if country == "St Christopher and Nevis"
replace vcode = 191 if country == "Stkitts"
replace vcode = 191 if country == "St Kitts"
replace vcode = 191 if country == "St Kitts"
replace vcode = 191 if country == "St Kitts and Nevis"
replace vcode = 191 if country == "St. Kitts and Nevis"
replace vcode = 191 if country == "St. Kitts And Nevis"
replace vcode = 191 if country == "St.kitts&nevis"
replace vcode = 191 if country == "St. Kitts & Nevis"
replace vcode = 192 if country == "Saint Lucia"
replace vcode = 192 if country == "SAINT LUCIA"
replace vcode = 192 if country == "Stlucia"
replace vcode = 192 if country == "St.lucia"
replace vcode = 192 if country == "St Lucia"
replace vcode = 192 if country == "St. Lucia"
replace vcode = 193 if country == "Grenadines"
replace vcode = 193 if country == "Saint Vincent"
replace vcode = 193 if country == "Saint Vincent and the Grenadines"
replace vcode = 193 if country == "St. Vincent & Grenadines"
replace vcode = 193 if country == "SAINT VINCENT AND THE GRENADINES"
replace vcode = 193 if country == "Stvincent"
replace vcode = 193 if country == "St Vincent"
replace vcode = 193 if country == "St Vincent"
replace vcode = 193 if country == "St. Vincent"
replace vcode = 193 if country == "St. Vincent & Grenadines"
replace vcode = 193 if country == "St Vincent and the Grenadines"
replace vcode = 193 if country == "St. Vincent and the Grenadines"
replace vcode = 193 if country == "St. Vincent And The Grenadines"
replace vcode = 193 if country == "ST. VINCENT AND THE GRENADINES"
replace vcode = 193 if country == "St.vincent&gre"
replace vcode = 194 if country == "Samoa"
replace vcode = 194 if country == "SAMOA"
replace vcode = 194 if country == "Samoa/Western Samoa"
replace vcode = 194 if country == "Western samoa"
replace vcode = 194 if country == "Western Samoa"
replace vcode = 195 if country == "San Marino"
replace vcode = 195 if country == "SAN MARINO"
replace vcode = 195 if country == "San Marino Republic of"
replace vcode = 196 if country == "Sao Tome & Principe"
replace vcode = 196 if country == "Sao Tomé & Principe"
replace vcode = 196 if country == "SAO TOMÉ & PRINCIPE"
replace vcode = 196 if country == "Saotome"
replace vcode = 196 if country == "São Tomé & Príncipe"
replace vcode = 196 if country == "Sao Tome and Principe"
replace vcode = 196 if country == "Sao Tome And Principe"
replace vcode = 196 if country == "SAO TOME AND PRINCIPE"
replace vcode = 196 if country == "São Tomé and Principe"
replace vcode = 196 if country == "SÃO TOMÉ AND PRINCIPE"
replace vcode = 196 if country == "Sao Tomé and Príncipe"
replace vcode = 196 if country == "SAO TOMÉ AND PRÍNCIPE"
replace vcode = 196 if country == "Sao Tome & Principe"
replace vcode = 196 if country == "Sao Tome + Principe"
replace vcode = 196 if country == "Sao Tome + Principe"
replace vcode = 196 if country == "Sao Tomé & Principe"
replace vcode = 196 if country == "SAO TOMÉ & PRINCIPE"
replace vcode = 197 if country == "Saudi arabia"
replace vcode = 197 if country == "SaudiArabia"
replace vcode = 197 if country == "Saudi Arabia"
replace vcode = 197 if country == "SAUDI ARABIA"
replace vcode = 198 if country == "Serbia"
replace vcode = 198 if country == "SERBIA"
replace vcode = 198 if country == "Serbia, Republic of"
replace vcode = 198 if country == "Yugoslavia"
replace vcode = 198 if country == "Yugoslavia - post 1991"
replace vcode = 198 if country == "Yugoslavia (Serbia)"
replace vcode = 199 if country == "Seycelles"
replace vcode = 199 if country == "Seychelles"
replace vcode = 199 if country == "SEYCHELLES"
replace vcode = 200 if country == "Singapore"
replace vcode = 200 if country == "SINGAPORE"
replace vcode = 201 if country == "Slovakia"
replace vcode = 201 if country == "SLOVAKIA"
replace vcode = 201 if country == "Slovak Rep"
replace vcode = 201 if country == "Slovak Republic"
replace vcode = 202 if country == "Slovenia"
replace vcode = 202 if country == "SLOVENIA"
replace vcode = 203 if country == "Solomon is."
replace vcode = 203 if country == "Solomon Is."
replace vcode = 203 if country == "Solomon Island"
replace vcode = 203 if country == "Solomonislands"
replace vcode = 203 if country == "Solomon Islands"
replace vcode = 203 if country == "SOLOMON ISLANDS"
replace vcode = 204 if country == "Tonga"
replace vcode = 204 if country == "TONGA"
replace vcode = 205 if country == "Tuvalu"
replace vcode = 205 if country == "TUVALU"
replace vcode = 206 if country == "Vanuatu"
replace vcode = 206 if country == "VANUATU"
replace vcode = 207 if country == "UAE"
replace vcode = 207 if country == "Unit. Arab Em."
replace vcode = 207 if country == "United arab e."
replace vcode = 207 if country == "Unitedarabemirate"
replace vcode = 207 if country == "United Arab Emirates"
replace vcode = 207 if country == "UNITED ARAB EMIRATES"
replace vcode = 208 if country == "Holy See (Vatican City State)"
replace vcode = 208 if country == "Vatican"
replace vcode = 208 if country == "Vatican City"
replace vcode = 208 if country == "VATICAN CITY"
replace vcode = 208 if country == "Vatican City State"
replace vcode = 209 if country == "Palestine (British Mandate)"
replace vcode = 209 if country == "Palestine/British_Mandate"
replace vcode = 209 if country == "PALESTINE (BRITISH MANDATE)"
replace vcode = 209 if country == "PALESTINE/BRITISH_MANDATE"
replace vcode = 210 if country == "Hungary"
replace vcode = 210 if country == "HUNGARY"
replace vcode = 255 if country == "Galicia and Lodomeria"
replace vcode = 349 if country == "Baden"
replace vcode = 350 if country == "Bavaria"
replace vcode = 351 if country == "Modena"
replace vcode = 352 if country == "Parma"
replace vcode = 353 if country == "Saxony"
replace vcode = 354 if country == "Tuscany"
replace vcode = 355 if country == "Wuerttemburg"
replace vcode = 355 if country == "Wurtemberg"
replace vcode = 355 if country == "Wurttemberg"
replace vcode = 356 if country == "Two Sicilies"
replace vcode = 357 if country == "Hanover"
replace vcode = 358 if country == "Hesse-Kassel"
replace vcode = 358 if country == "Hesse Electoral"
replace vcode = 359 if country == "Hesse-Darmstadt"
replace vcode = 359 if country == "Hesse Grand Ducal"
replace vcode = 360 if country == "Mecklenburg Schwerin"
replace vcode = 361 if country == "Papal States"
replace vcode = 362 if country == "Hamburg"
replace vcode = 363 if country == "Brunswick"
replace vcode = 364 if country == "Oldenburg "
replace vcode = 365 if country == "Saxe-Weimar-Eisenach"
replace vcode = 366 if country == "Nassau"
replace vcode = 373 if country == "Piedmont-Sardinia"
replace vcode = 408 if country == "Guadalupe"
replace vcode = 408 if country == "Guadalupe"
replace vcode = 409 if country == "Anguilla"
replace vcode = 410 if country == "Aruba"
replace vcode = 411 if country == "Bermuda"
replace vcode = 412 if country == "Caymanislands"
replace vcode = 412 if country == "Cayman Islands"
replace vcode = 412 if country == "Grand Cayman"
replace vcode = 413 if country == "Frenchguiana"
replace vcode = 413 if country == "French Guiana"
replace vcode = 414 if country == "Greenland"
replace vcode = 415 if country == "Guam"
replace vcode = 416 if country == "Nethantilles"
replace vcode = 416 if country == "Netherlands Antilles"
replace vcode = 417 if country == "Puertorico"
replace vcode = 417 if country == "Puerto rico"
replace vcode = 417 if country == "Puerto Rico"
replace vcode = 418 if country == "Usvirginislands"
replace vcode = 418 if country == "U.S. Virgin Islands"
replace vcode = 418 if country == "Virgin Islands - US"
replace vcode = 418 if country == "Virgin Islands (U.S.)"
replace vcode = 418 if country == "Virgin Islands, U.S."
replace vcode = 419 if country == "Americansamoa"
replace vcode = 419 if country == "American Samoa"
replace vcode = 420 if country == "Channel Islands"
replace vcode = 421 if country == "Curaao"
replace vcode = 421 if country == "Curacao"
replace vcode = 421 if country == "Curacao Island"
replace vcode = 421 if country == "Curacao Island"
replace vcode = 422 if country == "Faeroe Islands"
replace vcode = 422 if country == "Faeroes"
replace vcode = 422 if country == "Faroe Islands"
replace vcode = 423 if country == "Gibraltar"
replace vcode = 424 if country == "Isle of Man"
replace vcode = 425 if country == "Saint Martin"
replace vcode = 425 if country == "Saint Martin (French part)"
replace vcode = 425 if country == "St. Martin (French part)"
replace vcode = 426 if country == "Northern Mariana Islands"
replace vcode = 426 if country == "Northern Marianas"
replace vcode = 427 if country == "Sint Maarten"
replace vcode = 427 if country == "Sint Maarten (Dutch part)"
replace vcode = 428 if country == "Turksandcaicos"
replace vcode = 428 if country == "Turks and Caicos Islands"
replace vcode = 429 if country == "British Virgin Islands"
replace vcode = 429 if country == "Brvirginislands"
replace vcode = 429 if country == "Virgin Islands, British"
replace vcode = 430 if country == "Antarctica"
replace vcode = 431 if country == "Aland Islands"
replace vcode = 432 if country == "Saint Barthelemy"
replace vcode = 433 if country == "Bonaire"
replace vcode = 433 if country == "Bonaire, Sint Eustatius and Saba"
replace vcode = 433 if country == "Saba"
replace vcode = 433 if country == "Sint Eustatius"
replace vcode = 434 if country == "Cocos Island"
replace vcode = 434 if country == "Cocos Island"
replace vcode = 434 if country == "Cocos Islands"
replace vcode = 434 if country == "Cocos (Keeling) Islands"
replace vcode = 435 if country == "Cook Island"
replace vcode = 435 if country == "Cook Island"
replace vcode = 435 if country == "Cookislands"
replace vcode = 435 if country == "Cook Islands"
replace vcode = 436 if country == "Christmas Island"
replace vcode = 436 if country == "Christmas Island"
replace vcode = 436 if country == "Christmas Island"
replace vcode = 437 if country == "Western Sahara"
replace vcode = 438 if country == "Falkland Island"
replace vcode = 438 if country == "Falkland Island"
replace vcode = 438 if country == "Falkland Islands"
replace vcode = 438 if country == "Falkland Islands (Malvinas)"
replace vcode = 439 if country == "Guernsey"
replace vcode = 440 if country == "Jersey"
replace vcode = 441 if country == "Montserrat"
replace vcode = 442 if country == "Norfolk Island"
replace vcode = 443 if country == "Niue"
replace vcode = 444 if country == "Saint Pierre and Miquelon"
replace vcode = 445 if country == "Pitcairn"
replace vcode = 445 if country == "Pitcairn Islands"
replace vcode = 446 if country == "Ascension"
replace vcode = 446 if country == "Ascension"
replace vcode = 446 if country == "Ascension Island"
replace vcode = 446 if country == "Saint Helena"
replace vcode = 446 if country == "Saint Helena, Ascension and Tristan da Cunha"
replace vcode = 446 if country == "St Helena"
replace vcode = 447 if country == "Jan Mayen"
replace vcode = 447 if country == "Jan Mayen"
replace vcode = 447 if country == "Svalbard"
replace vcode = 447 if country == "Svalbard"
replace vcode = 447 if country == "Svalbard and Jan Mayen"
replace vcode = 448 if country == "United States Minor Outlying Islands"
replace vcode = 449 if country == "Isl Wallis"
replace vcode = 449 if country == "Isl Wallis"
replace vcode = 449 if country == "Wallis and Futuna"
replace vcode = 450 if country == "Mayotte"
replace vcode = 451 if country == "Canary Island"
replace vcode = 451 if country == "Canary Island"
replace vcode = 451 if country == "Canary Islands"
replace vcode = 451 if country == "Hawaii"
replace vcode = 452 if country == "Frenchpolynesia"
replace vcode = 452 if country == "French Polynesia"
replace vcode = 452 if country == "Heard Island"
replace vcode = 452 if country == "Heard Island"
replace vcode = 453 if country == "Chagos Archipelago"
replace vcode = 454 if country == "New Cale"
replace vcode = 454 if country == "Newcaledonia"
replace vcode = 454 if country == "New Caledonia"
replace vcode = 455 if country == "Reunion"
replace vcode = 455 if country == "Réunion"
replace vcode = 455 if country == "Reúnion"
replace vcode = 456 if country == "Württemberg"
replace vcode = 457 if country == "Hesse-Kassel (Electoral)"
replace vcode = 458 if country == "Hesse-Darmstadt (Ducal)"
replace vcode = 459 if country == "Mecklenburg-Schwerin"
replace vcode = 460 if country == "Tibet"
replace vcode = 461 if country == "Abkhazia"
replace vcode = 462 if country == "South Ossetia"
replace vcode = 463 if country == "Federal Republic of Central America"
replace vcode = 463 if country == "United Provinces of Central America"
replace vcode = 463 if country == "United Provinces Of Central America"
replace vcode = 464 if country == "Transvaal"
replace vcode = 465 if country == "Orange Free State"
replace vcode = 466 if country == "Gran Colombia"
replace vcode = 466 if country == "Great Colombia"
replace vcode = 467 if country == "Tokelau"
replace vcode = 467 if country == "Tokelau Island"
replace vcode = 468 if country == "French Southern Territories"
replace vcode = 469 if country == "South Georgia"
replace vcode = 469 if country == "South Georgia"
replace vcode = 469 if country == "South Georgia and the South Sandwich Islands"
replace vcode = 469 if country == "South Sandwich Islands"
replace vcode = 470 if country == "Azores"
replace vcode = 471 if country == "Galapagos Island"
replace vcode = 472 if country == "Madeira"
replace vcode = 472 if country == "Madeira Islands"
replace vcode = 473 if country == "Guadeloupe"
replace vcode = 474 if country == "Martinique"
